/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
SPDX-License-Identifier: Apache-2.0
-/
/-
Width-six four-point strict-improvement axiom audit:

  lake env lean comparator/PrintAxioms/WiderStrictImprovement.lean

This file audits both the wider endpoint theorem and the exact fixed-interface
ceiling.  Both modules are imported by the library root; the pinned build and
this audit are still required before either source candidate is called
formally certified.
-/
import Zeta23.StrictImprovement.ZetaWiderEndpointPassage
import Zeta23.StrictImprovement.WiderFixedInterfaceCeiling
import Zeta23.StrictImprovement.DirectFourPointInterface
import Zeta23.StrictImprovement.DirectCoreFourEnergy
import Zeta23.StrictImprovement.DirectZetaWiderAtD
import Zeta23.StrictImprovement.DirectZetaWiderCoreGain
import Zeta23.StrictImprovement.DirectZetaWiderSeamDefect
import Zeta23.StrictImprovement.DirectZetaWiderStrictSeamEventually
import Zeta23.StrictImprovement.DirectZetaWiderStrictFixedLambda
import Zeta23.StrictImprovement.DirectZetaWiderStrictConcrete
import Zeta23.StrictImprovement.DirectZetaWiderEndpointPassage
import Zeta23.StrictImprovement.SpectralZetaWiderEndpointPassage
import Zeta23.StrictImprovement.CertificateSlackZetaEndpointPassage
import Zeta23.StrictImprovement.WideRepairZetaEndpointPassage
import Zeta23.StrictImprovement.Q6SuperbinZetaEndpointPassage
import Zeta23.StrictImprovement.Q7SalvagedZetaEndpointPassage
import Zeta23.StrictImprovement.Q7FullSpectralZetaEndpointPassage

#print axioms Zeta23.StrictImprovement.zeta_wider_strict_simple_endpoint_rational
#print axioms Zeta23.StrictImprovement.common_budget_iff_le_widerFixedDeltaCeiling
#print axioms Zeta23.StrictImprovement.direct_six_edge_energy_stable
#print axioms Zeta23.StrictImprovement.directFourEtaLower_le_endpoint_gain
#print axioms Zeta23.StrictImprovement.packedCoreFour_direct_local_energy
#print axioms Zeta23.StrictImprovement.packedCoreFour_atD_direct_local_energy
#print axioms Zeta23.StrictImprovement.eventually_directAtDCoreGain_ge_fixed_eps
#print axioms Zeta23.StrictImprovement.seamA_mult2_atD_with_direct_explicit_gain
#print axioms Zeta23.StrictImprovement.eventually_seamA_mult2_atD_with_direct_explicit_gain
#print axioms Zeta23.StrictImprovement.zeta_direct_strict_simple_fixed_lam
#print axioms Zeta23.StrictImprovement.zeta_direct_strict_simple_endpoint_rational
#print axioms Zeta23.StrictImprovement.zeta_spectral_strict_simple_endpoint_rational
#print axioms Zeta23.StrictImprovement.zeta_certificate_slack_spectral_endpoint_rational
#print axioms Zeta23.StrictImprovement.sum_traceNorm_dependent_principal_le
#print axioms Zeta23.StrictImprovement.wideRepairBinReward_lower
#print axioms Zeta23.StrictImprovement.zeta_wide_repair_strict_simple_endpoint_rational
#print axioms Zeta23.StrictImprovement.zeta_wide_repair_strict_simple_endpoint_rational_207677
#print axioms Zeta23.StrictImprovement.zeta_wide_repair_strict_simple_endpoint_rational_207733
#print axioms Zeta23.StrictImprovement.zeta_wide_repair_strict_simple_endpoint_rational_211997
#print axioms Zeta23.StrictImprovement.zeta_q6Superbin_strict_simple_endpoint_rational
#print axioms Zeta23.StrictImprovement.zeta_q7Salvaged_strict_simple_endpoint_rational
#print axioms Zeta23.StrictImprovement.zeta_q7FullSpectral_strict_simple_endpoint_rational
